include: package:flutter_lints/flutter.yaml
linter:
  rules:
    unawaited_futures: true
    prefer_const_constructors: true
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  # refs:
  #  - https://pub.dev/packages/freezed#disabling-invalid_annotation_target-warning-and-warning-in-generates-files
  #  - https://github.com/rrousselGit/freezed/issues/488
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint